name: javascript-packages
on:
  push:
    paths:
      - build/javascript/package.json

jobs:
  run:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: npm run build
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repo
          uses: actions/checkout@v2
          with:
          # Make sure the actual branch is checked out when running on pull requests
            ref: ${{ github.head_ref }}

        - name: Build dependencies
          uses: actions/setup-node@v3
          with:
            node-version: '12'
        - run: cd build/javascript && npm run build

        - name: Commit changes
          uses: EndBug/add-and-commit@v5
          with:
            author_name: Owncast
            author_email: owncast@owncast.online
            message: "Commit updated Javascript packages"
            add: "build/javascript/package* webroot/js/web_modules"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
