name: Tests

on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: "^1"

      - name: Run tests
        run: go test ./...

  test-bsds:
    runs-on: macos-10.15
    strategy:
      matrix:
        os:
          - name: freebsd
            version: 12.2
          - name: openbsd
            version: 6.8

    steps:
      - uses: actions/checkout@v2

      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: "^1"

      - name: Run tests
        run: go test ./...

